### ISSUE TITLE
Different admin approach?

### ISSUE THREAD

**Issue by lechten** [pantajoe/revealjs-plugin-social-presence#1]
Hi Joe,

as discussed yesterday this is a reminder that the current way to register as teacher is not optimal yet.

Thank you again for this amazing plugin!

**Comment by pantajoe** [comment]
Thanks! Yeah, I think, it would be sufficient at first to add script like `bin/register-teacher` that could be invoked after the DB is setup with `bin/mikro-orm migration:up`:

```bash
bin/register-teacher -e jane.doe@example.com -n "Jane Doe" -p "supersecretpassword"
```

**Comment by pantajoe** [comment]
What do you think?

**Comment by lechten** [comment]
That would be great!

**Comment by pantajoe** [comment]
Just an FYI: I added sample configuration for nginx and production-ready deployment in the readme with this commit c3d7f834f934a216561233ebc9949cd9bc605f13

**Comment by pantajoe** [comment]
Now, while your backend is running with `docker-compose`, you can create a new teacher with the following command (from within the `backend/` directory):

```bash
bin/cli teachers register -e <email> -n <name> -p <password>
```

**Comment by lechten** [comment]
Great! Actually, I also use an nginx setting via port 443. With production settings, I was running into a PostgreSQL SSL problem, but didn't investigate further. This seems promising: `DISABLE_MIKRO_ORM_SSL: 'true'`

Maybe I find the time to test this over the weekend...

**Comment by pantajoe** [comment]
`DISABLE_MIKRO_ORM_SSL` should fix this, indeed. I had a similar problem for my demo in a prod environment 😅
